config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todos
  root to: "todos#index"
  put "/status/:id", to: "todos#status", as: "status"
  post "/status/:id", to: "todos#status"
  put "/migrate", to: "todos#migrate", as: "migrate"
  resources :friends, except: [:edit, :update]
  put "/friends/status", to: "friends#status", as: "status_friend"
  post "/friends/status", to: "friends#status"
  resources :shares, except: [:new, :edit, :update]
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :authenticate_user!
  before_action :friends_find, only: :index
  before_action :friend_find, only: :show

  def index
  end
  
  def show
  end

  def new
  end

  def create
    receiver = User.find_by(email: params[:email])
    unless receiver.nil?
      relation = Relation.new(sender_id: params[:sender_id], receiver_id: receiver.id)
      if relation.save
        flash[:notice] = "Request sent to #{receiver.email}, wait for acceptance !"
        redirect_to friends_path
      else
        flash[:alert] = relation.errors.full_messages
        redirect_to new_friend_path
      end
    else
      params[:email].blank? ? flash[:alert] = "Field can't be blank" : flash[:alert] = "We couldn't find #{params[:email]}"
      redirect_to new_friend_path
    end
  end

  def destroy
    user = User.find(params[:id])
    Relation.find_by(sender_id: current_user.id, receiver_id: user.id).nil? ?
    relation = Relation.find_by(sender_id: user.id, receiver_id: current_user.id) :
    relation = Relation.find_by(sender_id: current_user.id, receiver_id: user.id)
    relation.destroy
    Share.where(relation_id: relation.id).each {|share| share.destroy}
    flash[:notice] = "#{user.email} isn't your friend no more!"
    redirect_to friends_path
  end

  def status
    relation = Relation.find(params[:relation_id])
    if relation.update(status: true)
      flash[:notice] = "Request from #{User.find(relation.sender_id).email} accepted!"
      redirect_to friends_path
    else
      flash[:alert] = relation.errors.full_messages
      redirect_to friends_path
    end
  end

  private

  def friends_find
    relations_true = Relation.where(sender_id: current_user.id, status: true).or(Relation.where(receiver_id: current_user.id, status: true))
    @relations_false = Relation.where(receiver_id: current_user.id, status: false)
    friends_id = []
    relations_true.each do |relation|
      relation.sender_id == current_user.id ? friends_id << relation.receiver_id : friends_id << relation.sender_id
    end
    @friends = User.where(id: friends_id)
  end

  def friend_find
    if User.find_by(id: params[:id]).present?
      @friend = User.find(params[:id])
      todo_ids = []
      Share.where(sharer_id: current_user.id, receiver_id: @friend.id).each do |share|
        todo_ids << share.todo_id
      end
      @todos = Todo.where(id: todo_ids)
      redirect_to friends_path if Relation.find_by(sender_id: current_user.id, receiver_id: @friend.id).nil? && Relation.find_by(sender_id: @friend.id, receiver_id: current_user.id).nil?
    else
      redirect_to friends_path
    end
  end
end

app/helpers/friends_helper.rb
module FriendsHelper

  def friend_shares_count(friend_id)
    Share.where(sharer_id: current_user.id, receiver_id: friend_id).count
  end

end

app/views/friends/_delete_modal.html.erb
<button type="button" class="btn btn-danger btn-block mt-3" data-toggle="modal" data-target="#modalDelete">
  Delete friend
</button>
<div class="modal fade" id="modalDelete" tabindex="-1" role="dialog" aria-labelledby="modalDeleteLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalDeleteLabel">Confirm</h5>
      </div>
      <div class="modal-body">
        Do you really want to delete relation with <strong><%= @friend.email %></strong> and all shares?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= button_to "Delete", friend_path(@friend.id), method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/friends/_unshare_modal.html.erb
<button type="button" class="btn btn-danger ml-auto col-4 col-sm-3 ml-1" data-toggle="modal" data-target="#modalDismiss">
  Unshare
</button>
<div class="modal fade" id="modalDismiss" tabindex="-1" role="dialog" aria-labelledby="modalDismissLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalDismissLabel">Confirm</h5>
      </div>
      <div class="modal-body">
        Do you really want to unshare <strong><%= render_todo.title %></strong>?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= button_to "Unshare", share_path(shared?(current_user.id, @friend.id, render_todo.id).id), method: :delete,
        params: {sharer_id: render_todo.user_id, friend_id: @friend.id, todo_id: render_todo.id}, class: "btn btn-danger m-1" %>
      </div>
    </div>
  </div>
</div>

app/views/friends/index.html.erb
<div class="container">
  <% if @relations_false.present? %>
    <button class="btn btn-info btn-sm btn-block mt-3" type="button" data-toggle="collapse" data-target="#collapseInvitations" aria-expanded="false" aria-controls="collapseInvitations">
      Invitations<%= requests?(current_user.id).html_safe %>
    </button>
    <div class="collapse" id="collapseInvitations">
      <% @relations_false.each do |relation| %>
        <div class="card">
          <div class="card-body">
            <h5 class="card-title text-center"><%= User.find(relation.sender_id).email %></h5>
            <div class="row justify-content-center">
              <%= button_to "Accept", status_friend_path, params: {relation_id: relation.id}, method: :put, class: "btn btn-success btn-sm mr-2" %>
              <%= button_to "Discard", friend_path(User.find(relation.sender_id).id), method: :delete, class: "btn btn-danger btn-sm ml-2" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class="card my-3">
    <div class="card-header text-center">
      <span class="font-weight-bold">Friends</span>
    </div>
    <ul class="list-group list-group-flush">
      <% @friends.each do |friend| %>
        <li class="list-group-item">
          <div class="row">
            <div class="font-weight-bolder text-capitalize text-truncate col-7 col-sm-8"><%= friend.email %></div>
            <%= link_to "Show", friend_path(friend.id), class: "btn btn-primary ml-auto col-3" %>
          </div>
          <span class='span-prio badge badge-light'>Shared: <%= friend_shares_count(friend.id) %></span>
        </li>
      <% end %>
    </ul>
  </div>
  <%= link_to 'Add friend', new_friend_path, class: "btn btn-success btn-block mt-3" %>
</div>

app/views/friends/new.html.erb
<div class="container">
  <div class="card p-3 mt-3 bg-form">
    <%= form_with url: '/friends', method: :post do |form| %>
      <%= form.label 'User email' %>
      <%= form.text_field :email, class: "form-control mb-1" %>
      <%= form.hidden_field :sender_id, value: current_user.id %>
      <%= form.submit 'Send request', class: "btn btn-info btn-block mt-3" %>
    <% end %>
  </div>
</div>

app/views/friends/show.html.erb
<div class="container">
  <div class="card my-3">
    <div class="card-header text-center">
      <span class="font-weight-bold"><%= @friend.email %></span>
    </div>
  </div>
  <%= render "friends/delete_modal" %>
</div>