config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todos
  root to: "todos#index"
  put "/status/:id", to: "todos#status", as: "status"
  post "/status/:id", to: "todos#status"
  put "/migrate", to: "todos#migrate", as: "migrate"
  resources :friends, except: [:edit, :update]
  put "/friends/status", to: "friends#status", as: "status_friend"
  post "/friends/status", to: "friends#status"
  resources :shares, except: [:new, :edit, :update]
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :guest, optional: true
  belongs_to :user, optional: true
  belongs_to :share, optional: true

  validates :title, :description, presence: true
  validates :priority, inclusion: 0..2
  validates :status, inclusion: { in: [true, false] }

  private

  SORT = ["title", "title desc", "priority", "priority desc", "created_at", "created_at desc"]
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :todo_find, only: [:show, :edit, :status]
  before_action :todos_find, :todos_sort, only: [:index, :status]
  before_action :friends_find, only: :show


  def index
  end

  def show
  end

  def new
    @todo = Todo.new
  end

  def create
    todo = Todo.new(todo_params)
    if todo.save
      flash[:notice] = "#{todo.title} added!"
      redirect_to todo_path(todo.id)
    else
      flash.now[:alert] = todo.errors.full_messages
    end
  end

  def edit
  end

  def update
    todo = Todo.find(params[:id])
    if todo.update(todo_params)
      flash[:notice] = "#{todo.title} edited!"
      redirect_to todo_path(todo.id)
    else
      flash[:alert] = todo.errors.full_messages
      redirect_to edit_todo_path(todo.id)
    end
  end

  def destroy
    todo = Todo.find(params[:id])
    Share.where(todo_id: todo.id).each {|share| share.destroy}
    todo.destroy
    flash[:notice] = "#{todo.title} deleted!"
    redirect_to todos_path
  end

  def status
    if params[:from] == "share"
      @todo.update(status: @todo.status == false ? true : false)
      flash[:notice] = "#{@todo.title} #{@todo.status == false ? "to do!" : "done!"}"
      redirect_to shares_path
    else
      @todo.update(status: @todo.status == false ? true : false)
      flash.now[:notice] = "#{@todo.title} #{@todo.status == false ? "to do!" : "done!"}"
    end
  end

  def migrate
    todos = Todo.where(guest_id: session[:guest_id], user_id: nil)
    todos.each {|todo| todo.update(guest_id: nil ,user_id: current_user.id)}
    flash[:notice] = "Todos migrated!"
    redirect_to todos_path
  end

  private

  def todo_params
    params.require(:todo).permit(:title, :description, :priority, :status, :guest_id, :user_id)
  end

  def todo_find
    if Todo.find_by(id: params[:id]).present?
      @todo = Todo.find(params[:id])
      if user_signed_in?
        redirect_to todos_path if @todo.user_id != current_user.id && Share.find_by(sharer_id: @todo.user_id, todo_id: @todo.id, receiver_id: current_user.id).nil?
      else
        redirect_to todos_path if @todo.guest.id != session[:guest_id]
      end
    else
      redirect_to todos_path
    end
  end

  def todos_find
    if user_signed_in?
      @todos = Todo.where(user_id: current_user.id)
    else
      @todos = Guest.find(session[:guest_id]).todos
    end
  end

  def todos_sort
    if params[:sort]
      params[:sort] = "title" unless Todo::SORT.include?(params[:sort])
      @sort = params[:sort]
    else
      @sort = "title"
    end
  end

  def friends_find
    if user_signed_in?
      relations_true = Relation.where(sender_id: current_user.id, status: true).or(Relation.where(receiver_id: current_user.id, status: true))
      @relations_false = Relation.where(receiver_id: current_user.id, status: false)
      friends_id = []
      relations_true.each do |relation|
        relation.sender_id == current_user.id ? friends_id << relation.receiver_id : friends_id << relation.sender_id
      end
      @friends = User.where(id: friends_id)
    end
  end

end

app/helpers/todos_helper.rb
module TodosHelper
  
  def read_priority(priority)
    case priority
    when 0
      "Low"
    when 1
      "Medium"
    when 2
      "High"
    end
  end

  def read_status(status)
    status == true ? "Done" : "To Do"
  end
  
  def bg_status(status)
    "bg-card-done" if status == true
  end

  def time_display(time)
    seconds = time
    if seconds / 60 >= 1
      minutes = seconds / 60
      if minutes / 60 >= 1
        hours = minutes / 60
        if hours / 24 >= 1
          days = hours / 24
          return (days == 1 ? "1 day" : "#{days} days") + " #{hours % 24} h"
        else
          return "#{hours} h #{minutes % 60} min"
        end
      else
        return "#{minutes} min #{seconds % 60} sec"
      end
    else
    return "#{seconds} sec"
    end
  end

  def bg_priority(priority)
    case priority
    when 0
      "bg-prio-low"
    when 1
      "bg-prio-medium"
    when 2
      "bg-prio-high"
    end
  end

  def active_sort_link(sort)
    "active" if sort == params[:sort]
  end

  def todos_migrate?
    user_signed_in? && Todo.where(guest_id: session[:guest_id]).find_by(user_id: nil).present?
  end

  def todo_share?(todo_id)
    " | Shared" if Share.find_by(todo_id: todo_id).present?
  end

end

app/views/todos/_delete_modal.html.erb
<button type="button" class="btn btn-danger m-1" data-toggle="modal" data-target="#modalDelete">
  Delete
</button>
<div class="modal fade" id="modalDelete" tabindex="-1" role="dialog" aria-labelledby="modalDeleteLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalDeleteLabel">Confirm</h5>
      </div>
      <div class="modal-body">
        Do you really want to delete <strong><%= @todo.title %></strong>?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= link_to "Delete", todo_path(@todo.id), method: :delete, class: "btn btn-danger mx-1" %>
      </div>
    </div>
  </div>
</div>

app/views/todos/_form.html.erb
<div class="card p-3 mt-3 bg-form">
<%= form_with model: @todo do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title, class: "form-control mb-1" %>
  <%= form.label :description %>
  <%= form.text_area :description, class: "form-control mb-1" %>
  <%= form.label :priority %>
  <%= form.select :priority, options_for_select([["Low", 0], ["Medium", 1], ["High", 2]], @todo.priority), {}, {class: "form-control"} %>
  <%= form.hidden_field :status, value: @todo.status.nil? ? false : @todo.status %>
  <%= form.hidden_field :guest_id, value: session[:guest_id] unless user_signed_in? %>
  <%= form.hidden_field :user_id, value: current_user.id if user_signed_in? %>
  <%= form.submit class: "btn btn-info btn-block mt-3" %>
<% end %>
</div>

app/views/todos/_todos.html.erb
<div class="card my-3">
  <div class="card-header text-center <%= render_bg %>">
    <span class="font-weight-bold"><%= render_name %></span>
  </div>
  <ul class="list-group list-group-flush">
    <% @todos.where(status: render_status).order(@sort).each do |todo| %>
      <li class="list-group-item <%= bg_priority(todo.priority) %>">
        <div class="row">
          <div class="font-weight-bolder text-capitalize text-truncate col-6 col-sm-7"><%= todo.title %></div>
          <%= link_to "Show", todo_path(todo.id), class: "btn btn-primary ml-auto col-3" %>
          <%= button_to "#{render_btn_name}", status_path(todo.id), method: :put, remote: true, params: {sort: @sort}, class: "btn btn-#{render_btn_class} col-12", form_class: "col-3 col-sm-2" %>
        </div>
        <span class="badge span-prio text-muted">Priority: <%= read_priority(todo.priority) %><%= todo_share?(todo.id) %></span>
      </li>
    <% end %>
  </ul>
</div>

app/views/todos/create.js.erb
popup.innerHTML = "<%= j render "layouts/popup" %>";

app/views/todos/edit.html.erb
<div class="container">
  <%= render "todos/form" %>
  <%= link_to "Back", todo_path(@todo.id), class: "btn btn-primary btn-block" %>
</div>

app/views/todos/index.html.erb
<div class="container">
  <% if todos_migrate? %>
    <button class="btn btn-info btn-sm btn-block mt-3" type="button" data-toggle="collapse" data-target="#collapseMigrate" aria-expanded="false" aria-controls="collapseMigrate">
      Want to migrate?
    </button>
    <div class="collapse" id="collapseMigrate">
      <div class="card card-body text-center">
        We found that you have todos in Your session which aren't assigned with Your account!<br>
        To migrate them to Your account click the button bellow!
        <%= button_to "Migrate", migrate_path, method: :put, class: "btn btn-secondary btn-sm col-12 col-sm-8 col-md-6" %>
      </div>
    </div>
  <% end %>
  <div id="todos">
    <%= render partial: "todos/todos", locals: { render_name: "To Do", render_status: false, render_btn_name: [10003].pack('U*'), render_btn_class: "success", render_bg: "" } %>
    <%= render partial: "todos/todos", locals: { render_name: "Done", render_status: true, render_btn_name: [10005].pack('U*'), render_btn_class: "danger", render_bg: "bg-card-done" } %>
  </div>
</div>

app/views/todos/new.html.erb
<div class="container">
  <%= render "todos/form" %>
</div>

app/views/todos/show.html.erb
<div class="container">
  <div class="card text-center mt-3">
    <div class="card-header <%= bg_status(@todo.status) %>">
      <span class="font-weight-bold"><%= read_status(@todo.status) %></span>
    </div>
    <div class="card-body <%= bg_priority(@todo.priority) %>">
      <h5 class="card-title font-weight-bold"><%= @todo.title %></h5>
      <%= simple_format(@todo.description, class: "card-text") %>
      <%= link_to "Back", params[:friend].nil? ? todos_path : friend_path(params[:friend]) , class: "btn btn-primary m-1" %>
      <%= link_to "Edit", edit_todo_path(@todo.id), class: "btn btn-dark m-1" %>
      <%= render "shares/todo_share_modal" if user_signed_in? %>
      <%= render "todos/delete_modal" %>
      <span class="badge span-prio mt-5 text-muted">Priority: <%= read_priority(@todo.priority) %><%= todo_share?(@todo.id) %></span>
    </div>
    <div class="card-footer <%= bg_status(@todo.status) %>">
      <%= time_display(Time.now.to_i - @todo.created_at.to_i) %> ago
    </div>
  </div>
</div>

app/views/todos/status.js.erb
function deleteChilds(parent){
  while (parent.hasChildNodes()) {  
    parent.removeChild(parent.firstChild);
  }
}
deleteChilds(todos);
deleteChilds(popup);
popup.innerHTML = "<%= j render "layouts/popup" %>";
todos.innerHTML = "<%= j render partial: "todos/todos", locals: { render_name: "To Do", render_status: false, render_btn_name: [10003].pack('U*'), render_btn_class: "success", render_bg: "" } %><%= j render partial: "todos/todos", locals: { render_name: "Done", render_status: true, render_btn_name: [10005].pack('U*'), render_btn_class: "danger", render_bg: "bg-card-done" } %>";