config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todos
  root to: "todos#index"
  put "/status/:id", to: "todos#status", as: "status"
  post "/status/:id", to: "todos#status"
  put "/migrate", to: "todos#migrate", as: "migrate"
  resources :friends, except: [:edit, :update]
  put "/friends/status", to: "friends#status", as: "status_friend"
  post "/friends/status", to: "friends#status"
  resources :shares, except: [:new, :edit, :update]
end

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto pb-3">
  <div class="text-center">
    <span class="text-muted">MRozmus</span>
  </div>
</footer>

app/views/layouts/_guest_time.html.erb
<div class="alert alert-warning alert-dismissible fade show fixed-bottom text-center" role="alert">
  Session expire in <strong><%= time_display(86399 - (Time.now.to_i - Guest.find(session[:guest_id]).created_at.to_i)) %></strong>. 
  To avoid losing Your todo list <%= link_to "create account", new_user_registration_path, class: "alert-link" %>.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">ToDo</a>
  <button class="navbar-toggler rounded-pill" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav mr-auto">
      <%= link_to "Home", todos_path, class: "btn btn-light rounded-pill border mx-1 my-1 my-lg-0" %>
      <%= link_to "New", new_todo_path, class: "btn btn-light rounded-pill border mx-1 my-1 my-lg-0" %>
      <% if current_page?(root_path) || current_page?(todos_path) %>
       <div class="dropdown mx-1">
          <button class="btn btn-light dropdown-toggle rounded-pill border my-1 my-lg-0 btn-lg-block" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Sort
          </button>
          <div class="dropdown-menu text-center" aria-labelledby="dropdownMenuButton">
            <%= link_to "Title (A-Z)", todos_path(sort: "title"), class: "dropdown-item btn btn-light #{active_sort_link("title")}" %>
            <%= link_to "Title (Z-A)", todos_path(sort: "title desc"), class: "dropdown-item btn btn-light #{active_sort_link("title desc")}" %>
            <%= link_to "Priority (High)", todos_path(sort: "priority desc"), class: "dropdown-item btn btn-light #{active_sort_link("priority desc")}" %>
            <%= link_to "Priority (Low)", todos_path(sort: "priority"), class: "dropdown-item btn btn-light #{active_sort_link("priority")}" %>
            <%= link_to "Date (New)", todos_path(sort: "created_at desc"), class: "dropdown-item btn btn-light #{active_sort_link("created_at desc")}" %>
            <%= link_to "Date (Old)", todos_path(sort: "created_at"), class: "dropdown-item btn btn-light #{active_sort_link("created_at")}" %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="navbar-nav">
      <% if user_signed_in? %>
        <%= link_to "Friends#{requests?(current_user.id)}".html_safe, friends_path, class: "btn btn-light rounded-pill border mx-1 my-1 my-lg-0" %>
        <%= link_to "Share#{shares_count(current_user.id)}".html_safe, shares_path, class: "btn btn-light rounded-pill border mx-1 my-1 my-lg-0" %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-light rounded-pill border mx-1 my-1 my-lg-0" %>
      <% else %>
        <%= link_to "Sign in", new_user_session_path, class: "btn btn-light rounded-pill border mx-1 my-1 my-lg-0" %>
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-light rounded-pill border mx-1 my-1 my-lg-0" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_popup.html.erb
<% if flash[:notice] || flash[:alert] %>
  <div class="alert alert-<%= flash[:notice] ? "success" : "danger" %> alert-dismissible fade show" role="alert">
    <%= flash[:notice] if flash[:notice] %>
    <% if flash[:alert].class == Array %>
      <% flash[:alert].each do |e| %>
        <%= "- #{e}" %><br>
      <% end %>
    <% else %>
      <%= flash[:alert] %>
    <% end %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo - MRozmus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container" id="popup"><%= render "layouts/popup" %></div>
    <%= yield %>
    <%= render "layouts/guest_time" unless user_signed_in? %>
    <%= render "layouts/footer" %>
  </body>
</html>